services:
  # Base de données PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: agroconnect_db
    restart: always
    environment:
      POSTGRES_DB: agroconnect
      POSTGRES_USER: agrouser
      POSTGRES_PASSWORD: agropassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Backend Laravel (API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: agroconnect_backend
    restart: always
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: agroconnect
      DB_USERNAME: agrouser
      DB_PASSWORD: agropassword
    volumes:
      - ./backend:/var/www
    depends_on:
      - db

  # Frontend Angular (Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agroconnect_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
